In [1]:
import pandas as pd
import numpy as np
file="loan-data.csv"
rawdata=np.genfromtxt(file, delimiter=';',skip_header=1,autostrip=True)
rawdata

array([[4.8010226e+07,           nan, 3.5000000e+04, ...,           nan,
                  nan, 9.4529600e+03],
       [5.7693261e+07,           nan, 3.0000000e+04, ...,           nan,
                  nan, 4.6797000e+03],
       [5.9432726e+07,           nan, 1.5000000e+04, ...,           nan,
                  nan, 1.9698300e+03],
       ...,
       [5.0415990e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 2.1856400e+03],
       [4.6154151e+07,           nan,           nan, ...,           nan,
                  nan, 3.1994000e+03],
       [6.6055249e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 3.0190000e+02]])

In [2]:
rawdata.shape

(10000, 14)

In [3]:
np.isnan(rawdata)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False]])

In [4]:
np.isnan(rawdata).sum()

88005

In [5]:
np.nanmax(rawdata)

68616519.0

In [6]:
temp_fill=np.nanmax(rawdata)+1
temp_mean=np.nanmean(rawdata, axis=0)

In [7]:
temp_mean

array([5.40158092e+07,            nan, 1.52734632e+04,            nan,
       1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,
                  nan,            nan,            nan,            nan,
                  nan, 3.14385094e+03])

In [8]:
temp_stats=np.array([np.nanmin(rawdata,axis=0),
                     temp_mean,
                     np.nanmax(rawdata,axis=0)])

In [9]:
temp_stats

array([[3.73332000e+05,            nan, 1.00000000e+03,            nan,
        1.00000000e+03,            nan, 6.00000000e+00, 3.14200000e+01,
                   nan,            nan,            nan,            nan,
                   nan, 0.00000000e+00],
       [5.40158092e+07,            nan, 1.52734632e+04,            nan,
        1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,
                   nan,            nan,            nan,            nan,
                   nan, 3.14385094e+03],
       [6.86165190e+07,            nan, 3.50000000e+04,            nan,
        3.50000000e+04,            nan, 2.89900000e+01, 1.37297000e+03,
                   nan,            nan,            nan,            nan,
                   nan, 4.19136200e+04]])

In [10]:
column_strings=np.argwhere(np.isnan(temp_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [11]:
column_numeric=np.argwhere(np.isnan(temp_mean)==False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [12]:
import pandas as pd
import numpy as np
file="loan-data.csv"
loandatastrings=np.genfromtxt(file,
                      delimiter=';',
                      skip_header=1,
                      autostrip=True,
                     usecols=column_strings,
                     dtype='str')
loandatastrings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
        'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
        'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726',
        'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
        'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
        'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249',
        'IL']], dtype='<U69')

In [13]:
import pandas as pd
import numpy as np
file="loan-data.csv"
loandatanumeric=np.genfromtxt(file,
                      delimiter=';',
                      skip_header=1,
                      autostrip=True,
                     usecols=column_numeric,
                     dtype='int32')
loandatanumeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000,       -1,      938,     4679],
       [59432726,    15000,    15000,       -1,      494,     1969],
       ...,
       [50415990,    10000,    10000,       -1,       -1,     2185],
       [46154151,       -1,    10000,       16,      354,     3199],
       [66055249,    10000,    10000,       -1,      309,      301]])

In [16]:
import pandas as pd
import numpy as np
file="loan-data.csv"
loandatanumeric=np.genfromtxt(file,
                      delimiter=';',
                      skip_header=1,
                      autostrip=True,
                     usecols=column_numeric,
                     filling_values=temp_fill,
                              dtype='int32'
                             )
loandatanumeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

In [17]:
import pandas as pd
import numpy as np
file="loan-data.csv"
header_full=np.genfromtxt(file,
                      delimiter=';',
                      skip_footer=rawdata.shape[0],
                      autostrip=True,
                     dtype='str')
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term',
       'int_rate', 'installment', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state', 'total_pymnt'],
      dtype='<U19')

In [18]:
header_strings,header_numeric=header_full[column_strings],header_full[column_numeric]
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [19]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U19')